out_dir : ./model  # 输出目录
url_tag : colname # 结构体标签默认是json，可以改成colname或者其他自定义标签

db_info:
    host : 172.30.10.15
    port : 3306
    username : aitrack
    password : 123456
    database : aitrack
    type: 0 # 数据库类型:0:mysql , 1:sqlite
self_type_define: # 自定义数据类型映射
    datetime: time.Time
    time: time.Time
    date: string
out_file_name: "" # 自定义生成文件名
web_tag_type: 1 # json tag类型 0: 小驼峰 1: 下划线

